-- MySQL Script generated by MySQL Workbench
-- Mon Jan 14 12:20:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema barber_demo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema barber_demo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `barber_demo` DEFAULT CHARACTER SET utf8 ;
USE `barber_demo` ;

-- -----------------------------------------------------
-- Table `barber_demo`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_demo`.`users` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(68) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone_number` INT(9) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC),
  UNIQUE INDEX `email_UNIQUE` (`username` ASC),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `barber_demo`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_demo`.`orders` (
  `id_order` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `price` INT(2) NOT NULL,
  `service` VARCHAR(45) NOT NULL,
  `id_user` INT(11) NOT NULL,
  PRIMARY KEY (`id_order`),
  UNIQUE INDEX `id_order_UNIQUE` (`id_order` ASC),
  UNIQUE INDEX `date_UNIQUE` (`date` ASC),
  INDEX `fk_orders_users1_idx` (`id_user` ASC),
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `barber_demo`.`users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `barber_demo`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_demo`.`roles` (
  `id_role` INT(11) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_role`),
  UNIQUE INDEX `id_role_UNIQUE` (`id_role` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `barber_demo`.`users_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barber_demo`.`users_roles` (
  `user_id` INT(11) NOT NULL,
  `role_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `FK_ROLE_idx` (`role_id` ASC),
  CONSTRAINT `FK_ROLE`
    FOREIGN KEY (`role_id`)
    REFERENCES `barber_demo`.`roles` (`id_role`),
  CONSTRAINT `FK_USER_05`
    FOREIGN KEY (`user_id`)
    REFERENCES `barber_demo`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
